name: cafe
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Manrope
      fonts:
        # - asset: fonts/manrope_variable_font_wght.ttf
        # - asset: fonts/Manrope-Bold.ttf
        # - asset: fonts/Manrope-ExtraBold.ttf
        # - asset: fonts/Manrope-ExtraLight.ttf
        # - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Medium.ttf
        # - asset: fonts/Manrope-SemiBold.ttf

# flutter_native_splash-development.yaml
flutter_native_splash:
  web: false
  android: true
  ios: true 
  color: "#089082"
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    icon_background_color: "#089082"

  
